default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: challenge2you_development

test:
  <<: *default
  database: challenge2you_test

production:
  <<: *default
  database: challenge2you_production
  username: challenge2you
  password: <%= ENV['CHALLENGE2YOU_DATABASE_PASSWORD'] %>